---
configuration:
  neutron_config:
    data:
      DEFAULT/debug:
        value: True
  neutron_api_config:
    data:
      test/test:
        value: 20
  neutron_plugin_ml2:
    data:
      test/polling_interval:
        value: 10
